Repository KangHayeonn/together-party-tonight-server, pull requests merged in 2023-07, with the labels that each got.

#67 [BUGFIX] : image 업로드 이슈 해결
  README.md
  topato.png
  topato_ERD.png
Labels: 🐛 bug

#56 정산기능 추가, 채팅 에러 수정 및 리팩토링
  togetherPartyTonight/build.gradle
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/billing/controller/BillingController.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/billing/dto/BillingHistoryDto.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/billing/dto/BillingPaymentRequestDto.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/billing/dto/BillingPaymentResponseDto.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/billing/dto/ClubBillingHistoryRequestDto.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/billing/dto/ClubBillingHistoryResponseDto.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/billing/dto/CreateBillingRequestDto.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/billing/dto/CreateBillingResponseDto.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/billing/dto/MyBillingHistoryResponseDto.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/billing/entity/Billing.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/billing/entity/BillingHistory.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/billing/entity/BillingState.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/billing/exception/BillingErrorCode.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/billing/exception/BillingException.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/billing/repository/BillingHistoryRepository.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/billing/repository/BillingRepository.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/billing/service/BillingService.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/chat/controller/ChatController.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/chat/dto/ChatDto.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/chat/dto/ChatRoomListResponseDto.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/chat/dto/ChatSendRequestDto.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/chat/dto/CreateChatRoomRequest.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/chat/entity/Chat.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/chat/service/ChatService.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/club/entity/ClubMember.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/club/repository/ClubMemberRepository.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/member/service/MemberDetailsService.java
  togetherPartyTonight/src/test/java/webProject/togetherPartyTonight/domain/chat/service/ChatServiceTest.java
Labels: ✋ code-review, ✨ add

#61 review작성, 수정, 삭제시 member의 평점 정보 수정
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/review/entity/Review.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/review/service/ReviewService.java
Labels: 🌈 update, ✋ code-review

#65 태그 검색할 때 사용하는 api 구현
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/search/controller/SearchController.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/search/repository/SearchRepository.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/search/service/SearchService.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/infra/S3/S3Service.java
  togetherPartyTonight/src/test/java/webProject/togetherPartyTonight/club/info/ClubRepositoryTest.java
  togetherPartyTonight/src/test/java/webProject/togetherPartyTonight/club/info/ClubServiceTest.java
  togetherPartyTonight/src/test/java/webProject/togetherPartyTonight/domain/club/searchTagTest.java
Labels: ✋ code-review, ✨ add

#69 [UPDATE] : 토큰 만료 응답 세분화, 일반 로그인 loadByusername변경
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/member/auth/jwt/JwtFilter.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/member/exception/errorCode/TokenErrorCode.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/member/service/AuthService.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/member/service/MemberDetailsService.java
Labels: 🌈 update, ✋ code-review

#71 [ADD] : alert 관련 entity, 기본 crud 추가, 알림 시 소켓 메시지 발송
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/alert/controller/AlertController.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/alert/dto/AlertDto.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/alert/dto/AlertListRequestDto.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/alert/dto/AlertListResponseDto.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/alert/dto/AlertUnreadCountDto.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/alert/dto/alertContent/AlertApplyData.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/alert/dto/alertContent/AlertApproveData.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/alert/dto/alertContent/AlertBillingData.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/alert/dto/alertContent/AlertBillingPayData.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/alert/dto/alertContent/AlertChatData.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/alert/dto/alertSocketContent/AlertApplySocketContent.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/alert/dto/alertSocketContent/AlertApproveSocketContent.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/alert/dto/alertSocketContent/AlertBillingPaySocketContent.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/alert/dto/alertSocketContent/AlertBillingSocketContent.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/alert/dto/alertSocketContent/AlertChatSocketContent.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/alert/dto/alertSocketContent/AlertDataSocketContent.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/alert/dto/alertSocketContent/AlertSocketContent.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/alert/dto/alertSocketMessage/SocketApplyData.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/alert/entity/Alert.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/alert/entity/AlertType.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/alert/exception/AlertErrorCode.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/alert/repository/AlertRepository.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/alert/service/AlertService.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/billing/service/BillingService.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/chat/entity/ChatRoom.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/chat/service/ChatService.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/global/config/SecurityConfig.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/global/config/WebConfig.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/global/config/WebSocketConfig.java
Labels: ✋ code-review, ✨ add

#73 clubName 길이제한 예외처리, meetingDate 유효성 검증 해제
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/club/dto/request/CreateClubRequestDto.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/club/dto/response/MyOwnedClubDto.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/club/entity/Club.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/club/entity/ClubCategory.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/club/service/ClubJoinService.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/club/service/ClubService.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/search/controller/SearchController.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/search/repository/SearchRepository.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/search/service/SearchService.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/global/common/service/ResponseService.java
  togetherPartyTonight/src/test/java/webProject/togetherPartyTonight/domain/club/randomTagTest.java
  togetherPartyTonight/src/test/java/webProject/togetherPartyTonight/domain/club/s3Test.java
  togetherPartyTonight/src/test/java/webProject/togetherPartyTonight/domain/club/searchCategoryTest.java
Labels: 🌈 update, ✋ code-review, 🐛 bug

#75 [UPDATE] : 유저정보응답 dto 자기소개 추가
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/member/auth/mail/MailService.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/member/dto/response/MemberInfoResponseDto.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/global/config/WebConfig.java
  togetherPartyTonight/src/main/resources/templates/emailAuth.html
Labels: 🌈 update, ✋ code-review, 🐛 bug

#82 [UPDATE] : 채팅 나가기 알림 추가, 알림관련 리팩토링. 체팅 발송자 추가, 채팅방 이름 변경 추가, 채팅방 나가기 추가
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/alert/controller/AlertController.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/alert/dto/alertContent/AlertApplyData.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/alert/dto/alertContent/AlertApproveData.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/alert/dto/alertContent/AlertBillingData.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/alert/dto/alertContent/AlertBillingPayData.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/alert/dto/alertContent/AlertChatData.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/alert/dto/alertContent/AlertChatRoomLeaveData.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/alert/dto/alertSocketContent/AlertApplySocketContent.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/alert/dto/alertSocketContent/AlertApproveSocketContent.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/alert/dto/alertSocketContent/AlertBillingPaySocketContent.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/alert/dto/alertSocketContent/AlertBillingSocketContent.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/alert/dto/alertSocketContent/AlertChatSocketContent.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/alert/entity/Alert.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/alert/entity/AlertType.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/alert/exception/AlertException.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/alert/repository/AlertRepository.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/alert/service/AlertService.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/billing/dto/BillingPaymentRequestDto.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/billing/dto/BillingPaymentResponseDto.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/billing/entity/Billing.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/billing/exception/BillingException.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/chat/controller/ChatController.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/chat/dto/ChatDto.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/chat/dto/ChatRoomLeaveRequest.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/chat/dto/ChatRoomRenameRequestDto.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/chat/dto/ChatSocketMessage.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/chat/dto/CreateChatRoomRequest.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/chat/entity/Chat.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/chat/entity/ChatRoom.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/chat/repository/ChatRepository.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/chat/repository/ChatRoomRepository.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/chat/service/ChatService.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/global/config/SecurityConfig.java
  togetherPartyTonight/src/main/resources/static/index.html
Labels: 🌈 update, ✋ code-review, ✨ add

#84 default image, clubCategory관련 이슈 수정
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/club/dto/request/CreateClubRequestDto.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/club/entity/ClubCategory.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/club/exception/ClubErrorCode.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/club/service/ClubService.java
Labels: 🌈 update, ✋ code-review

#77 [BUGFIX] : 레디스 오류에 대한 검증위한 로깅 추가
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/member/service/SocialLoginService.java
Labels: ✋ code-review, 🐛 bug

#86 [ADD] : mysql 인덱스 최적화, 기본이미지 default 수정
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/club/entity/ClubMember.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/club/entity/ClubSignup.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/member/entity/Member.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/member/service/MemberService.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/review/entity/Review.java
  togetherPartyTonight/src/main/resources/templates/emailAuth.html
Labels: ✋ code-review, ✨ add

#90 club, comment entity에 인덱스 추가
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/club/controller/ClubController.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/club/entity/Club.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/comment/entity/Comment.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/review/controller/ReviewController.java
Labels: ✋ code-review, ✨ add

#94 배포 사항 동기화 및 닉네임 관련 수정
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/club/service/ClubJoinService.java
Labels: 🌈 update, ✋ code-review

#97 [UPDATE] : 레디스 비밀번호받기 위한 레디스설정
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/global/config/RedisConfig.java
Labels: 🌈 update, ✋ code-review

#99 [UPDATE] : 정산 예외처리 글로벌 핸들링, 알림 미발송 이슈 해결, 채팅방 순서 reverse, 레디스 delete …
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/alert/controller/AlertController.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/alert/service/AlertService.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/billing/exception/BillingException.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/billing/service/BillingService.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/chat/service/ChatService.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/comment/service/CommentService.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/member/controller/AuthController.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/search/service/SearchService.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/global/common/service/RedisService.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/global/config/RedisConfig.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/global/websocket/WebSocketService.java
Labels: 🌈 update, ✋ code-review
