Repository KangHayeonn/together-party-tonight-server, pull requests merged in 2023-08, with the labels that each got.

#95 [UPDATE] : 마이페이지 쪽 연동하면서 생긴 이슈들 수정
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/billing/entity/Billing.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/billing/entity/BillingHistory.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/club/controller/ClubController.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/club/dto/request/UpdateClubRequestDto.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/club/dto/response/ApplicationDto.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/club/dto/response/ClubReviewResponseListDto.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/club/dto/response/GetClubResponseDto.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/club/dto/response/MyOwnedClubDto.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/club/dto/response/ReceivedApplicationDto.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/club/entity/Club.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/club/entity/ClubMember.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/club/exception/ClubErrorCode.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/club/repository/ClubRepository.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/club/repository/ClubSignupRepository.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/club/service/ClubJoinService.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/club/service/ClubService.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/comment/controller/CommentController.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/comment/dto/response/GetCommentResponseDto.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/comment/service/CommentService.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/review/controller/ReviewController.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/review/dto/response/CreateReviewResponseDto.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/review/repository/ReviewRepository.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/review/service/ReviewService.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/search/controller/SearchController.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/search/entity/Tag.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/search/repository/TagRepository.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/search/service/SearchService.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/global/config/SecurityConfig.java
Labels: 🌈 update, ✋ code-review

#101 [UPDATE] : billing request 주소 변경
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/billing/controller/BillingController.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/global/websocket/WebSocketService.java
Labels: 🌈 update, ✋ code-review

#105 [UPDATE] : alert delete / 제거
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/alert/controller/AlertController.java
Labels: 🌈 update, ✋ code-review

#104 [UPDATE] : npe 부분 수정
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/club/dto/response/ReceivedApplicationDto.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/club/service/ClubJoinService.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/club/service/ClubService.java
Labels: 🌈 update, ✋ code-review, 🐛 bug

#111 프로필 이미지 변경 에러 이슈 fix
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/member/service/MemberService.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/global/config/RedisConfig.java
Labels: ✋ code-review, 🐛 bug

#114 [UPDATE] : 모임장 정산내역 신청에대한 예외 추가
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/billing/service/BillingService.java
Labels: 🌈 update, ✋ code-review

#115 [UPDATE] : 정산 신청, 유저 프로필 이미지, 모임별 리뷰, 리뷰 상세, 검색 인덱스 수정
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/billing/service/BillingService.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/club/service/ClubService.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/member/service/MemberService.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/review/dto/response/GetReviewDetailResponseDto.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/review/service/ReviewService.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/search/repository/SearchRepository.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/search/service/SearchService.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/global/config/RedisConfig.java
Labels: 🌈 update, ♻ refactor

#116 [BUGFIX] : 정산 결제에서 결제내역 멤버와 같아도 에러가 나오는 현상 수정
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/billing/service/BillingService.java
Labels: 🌈 update, ✋ code-review

#117 [UPDATE] : 정산내역에서 유저 프로필 이미지추가
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/alert/service/AlertService.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/billing/dto/BillingHistoryDto.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/billing/service/BillingService.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/chat/repository/ChatRepository.java
  togetherPartyTonight/src/main/java/webProject/togetherPartyTonight/domain/chat/service/ChatService.java
Labels: 🌈 update, ✋ code-review
